name: Deploy static content to Pages
run-name: Auto Update Nodes

on:
  #push
  schedule:
    - corn: 0 8 * * *

permissions:
  contents: write  

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Libraries
        run: pip install -r .\requirements.txt
      - name: Get Nodes
        run: python3 .\GetNodes.py
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .\